export {default as Navbar}  from './Navbar/Navbar'
export {default as OurStory}  from './OurStory/OurStory'
export {default as Services}  from './Services/Services'
export {default as Founders}  from './Founders/Founders'
export {default as Gallery}  from './Gallery/Gallery'
export {default as Process}  from './Process/Process'
export {default as Guiding}  from './Guiding/Guiding'